
name: Frontend CI/CD

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend  # Adjust this to your frontend directory

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'  # Adjust path as needed
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint code
      run: npm run lint
      
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build  # Adjust this to your build output directory