name: Frontend CI Pipeline

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: [self-hosted, cmrs-github-runner-03]

    strategy:
      matrix:
        node-version: [ '20.x' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
          node_modules/.cache
        key: build-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          build-cache-${{ runner.os }}-

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
      continue-on-error: false

    - name: Run Prettier
      run: npm run prettier:check
      continue-on-error: false

    - name: Build (optimized)
      run: |
        export GENERATE_SOURCEMAP=false
        npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: dist/
        retention-days: 3

