
name: Frontend CI/CD

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        node-version: [ '22.x' ]  

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'  

    - name: Install dependencies
      run: npm ci
    
    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
    
    - name: Build
      run: npm run build
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build